### ISSUE TITLE
Wrapping removes context of the actual error

### ISSUE THREAD

**Issue by dougstead** [go-qbit/multistate#8]
https://github.com/go-qbit/multistate/blob/66ab4eba201fa7df863712adeeb3e354288db3d6/multistate.go#L246

The error wrapping here takes the string value of the actual error which was thrown, rather than wrapping the error itself. 
The fmt.Errorf wrapping should wrap the string value of the execute_action_error and wrap the error which was thrown, so that errors can be handled effectively outside of the state machine.

`fmt.Errorf("%s: %w", err.Error(), ErrExecutionAction)`
should become:
`fmt.Errorf("%s: %w", ErrExecutionAction.Error(), err)`

**Comment by sergei-svistunov** [comment]
v0.9.2

**Comment by utrack** [comment]
Hi @sergei-svistunov, I believe the issue is still there - using `%s` verb for the original error still converts it to a string and removes any type/code metadata.

Swapping `%s: %w` for `%w: %s` will fix the issue. Another way would be to use `%w %w` and make our platform support errors made via stdlib `errors.Join`.

**Comment by sergei-svistunov** [comment]
v0.9.3
